import { evaluateOpportunity } from './decision-engine.js';
import { calculateOfferEconomics } from './v4-offer-economics-engine.js';
import { buildRadarOpportunity } from './radar-orchestrator.js';
import { toOpportunityViewModel } from './ui-adapter.js';

export const DEMO_OPPORTUNITY = Object.freeze({
  id:'empty-dashboard', product:'Aucune opportunité active', source:'—', country:'—',
  offer:{salePrice:0,landedCost:0,variableFees:0,cac:0,targetMargin:30,visitors:0,conversionRate:0},
  demandScore:0,sourcingScore:0,profitabilityScore:0,riskScore:0,confidence:0,
  marketingScore:0,easeOfTest:0,availability:0,potential:0,landedCostScore:0,
});
function engineInput(o){return{demand:o.demandScore,marketing:o.marketingScore??o.demandScore,sourcing:o.sourcingScore,profitability:o.profitabilityScore,confidence:o.confidence,economics:calculateOfferEconomics(o.offer)}}
export function calculateDashboardState(o=DEMO_OPPORTUNITY){const economics=calculateOfferEconomics(o.offer);const decision=evaluateOpportunity({...o,landedCost:o.offer.landedCost,margin:economics.netContributionMargin});const canonical=buildRadarOpportunity({id:o.id,product:o.product,source:o.source,country:o.country,radarSignals:engineInput(o),dimensions:{potential:o.potential,demand:o.demandScore,margin:economics.netContributionMargin,availability:o.availability,landedCost:o.landedCostScore,risk:o.riskScore,easeOfTest:o.easeOfTest,dataConfidence:o.confidence},economics,decision});return Object.freeze({economics,decision,opportunity:canonical,viewModel:toOpportunityViewModel(canonical)});}
const money=v=>`${Number(v).toFixed(2).replace('.',',')} €`;const setText=(n,v)=>{if(n)n.textContent=v};
function setGauge(node,score){if(!node)return;const n=Math.max(0,Math.min(100,Number(score)||0));node.style.background=`conic-gradient(var(--green,#79df31) 0 ${n*3.6}deg,#24302d ${n*3.6}deg)`;setText(node.querySelector('b'),n?String(Math.round(n)):'—')}
function setDecisionStyle(node,decision){if(!node)return;node.classList.remove('good');node.style.color=decision==='TESTER'?'var(--green,#79df31)':decision==='EVITER'?'var(--red,#ef5b52)':'var(--orange,#f0a52b)'}
function render(state){const vm=state.viewModel,cards=[...document.querySelectorAll('.kpis .kpi')],empty=state.opportunity.product==='Aucune opportunité active';if(cards.length>=5){setGauge(cards[0].querySelector('.gauge'),empty?0:vm.score);setText(cards[0].querySelector('.sub'),empty?'Aucune donnée active':Number(vm.score)>=75?'Score opportunité élevé':Number(vm.score)>=50?'Potentiel à approfondir':'Potentiel faible');setText(cards[1].querySelector('.val'),empty?'—':vm.dimensions.landedCost);setText(cards[2].querySelector('.val'),empty?'—':vm.dimensions.margin);setText(cards[3].querySelector('.val'),empty?'—':money(vm.economics.maxCacAtTargetMargin));setText(cards[4].querySelector('.decision'),empty?'ATTENDRE':vm.decision);setText(cards[4].querySelector('.sub'),empty?'Lancer un sourcing pour obtenir des données':vm.decisionReason);setDecisionStyle(cards[4].querySelector('.decision'),empty?'ATTENDRE':vm.decision)}const signals=[...document.querySelectorAll('.signals .sig')];if(signals.length>=5){setText(signals[0].querySelector('span'),empty?'—':`${state.opportunity.dimensions.potential??0}/100`);setText(signals[1].querySelector('span'),empty?'—':`${state.opportunity.dimensions.demand??0}/100`);setText(signals[2].querySelector('span'),empty?'—':`${state.opportunity.dimensions.margin??0}%`);setText(signals[3].querySelector('span'),empty?'—':`${state.opportunity.dimensions.risk??0}/100`);setText(signals[4].querySelector('span'),empty?'P0 · aucune preuve':`Preuve : ${state.opportunity.evidenceLevel??'P0'}`)}const badges=[...document.querySelectorAll('.pbadge')];if(badges[0])badges[0].textContent=empty?'P0 · aucune preuve':`${state.opportunity.evidenceLevel??'P0'} · niveau de preuve`;const d=document.querySelector('.diagnostic');if(d)d.textContent=empty?'Aucune opportunité active. Lance un sourcing pour alimenter le radar avec des données vérifiables.':`Diagnostic : ${state.economics.status==='healthy'?'Économie compatible avec un test.':state.economics.status==='thin_margin'?'Marge trop fine pour la cible.':'Économie déficitaire.'} Contribution après acquisition : ${money(state.economics.contributionAfterAds)} par commande. La preuve fournisseur et la validation qualité restent déterminantes avant achat.`;const row=document.querySelector('.table tbody');if(row&&empty)row.innerHTML='<tr><td colspan="4" style="color:#8d979e">Aucune opportunité active — lancez un sourcing pour alimenter cette liste.</td></tr>'}
function feedback(text){document.querySelector('[data-v4-feedback]')?.remove();const el=document.createElement('div');el.dataset.v4Feedback='true';el.textContent=text;Object.assign(el.style,{position:'fixed',right:'18px',bottom:'18px',zIndex:'9999',padding:'10px 13px',border:'1px solid #5b4a27',borderRadius:'8px',background:'#11100d',color:'#d7b45a',font:'600 11px Inter,system-ui,sans-serif',boxShadow:'0 10px 30px #0008'});document.body.appendChild(el);window.setTimeout(()=>el.remove(),1800)}
function sourcingStatus(product,stage,done=false){document.querySelector('[data-v4-sourcing-run]')?.remove();const el=document.createElement('div');el.dataset.v4SourcingRun='true';Object.assign(el.style,{position:'fixed',left:'50%',top:'18px',transform:'translateX(-50%)',zIndex:'10000',width:'min(520px,calc(100vw - 24px))',padding:'12px 14px',border:`1px solid ${done?'#315c3d':'#5b4a27'}`,borderRadius:'10px',background:'#0d1012',color:'#f3f4f2',font:'600 11px Inter,system-ui,sans-serif',boxShadow:'0 14px 40px #0009'});el.innerHTML=`<div style="display:flex;justify-content:space-between"><span>SOURCING</span><b style="color:${done?'#79df31':'#d7b45a'}">${done?'TERMINÉ':'EN COURS'}</b></div><div style="margin-top:6px;color:#9da4a8">${product}</div><div style="margin-top:7px;color:${done?'#79df31':'#d7b45a'}">Étape : ${stage}</div>`;document.body.appendChild(el);if(done)window.setTimeout(()=>el.remove(),2600)}
function startSourcing(product){const name=String(product||'').trim();if(!name)return null;sourcingStatus(name,'Découverte');const next={...DEMO_OPPORTUNITY,id:`manual-${Date.now()}`,product:name};initDashboardRuntime(next);const stages=['Découverte','Analyse','Scoring','Rentabilité','Validation','Décision'];let i=0;const timer=window.setInterval(()=>{i+=1;if(i>=stages.length){window.clearInterval(timer);sourcingStatus(name,'Décision disponible',true);feedback(`Sourcing terminé : ${name}`);return}sourcingStatus(name,stages[i])},450);return next}
function scrollToTarget(selector,label){const target=document.querySelector(selector);if(target){target.scrollIntoView({behavior:'smooth',block:'center'});feedback(label)}else feedback(`${label} : section indisponible`)}
function addSectionButtons(){if(document.querySelector('[data-v4-section-actions]'))return;const configs=[['Radar Sourcing','Ouvrir le radar','radar'],['Opportunités prioritaires','Analyser les opportunités','opportunities'],['Diagnostic décisionnel','Voir le diagnostic','diagnostic'],['Validation avant achat','Ouvrir la validation','qc']];configs.forEach(([label,text,key])=>{const panel=[...document.querySelectorAll('.panel')].find(p=>p.querySelector('h2')?.textContent.trim()===label);if(!panel)return;const head=panel.querySelector('.panelHead');if(!head)return;const b=document.createElement('button');b.className='btn';b.type='button';b.dataset.v4SectionAction=key;b.textContent=text;b.style.padding='7px 10px';b.style.fontSize='10px';head.appendChild(b)});document.querySelector('.content')?.setAttribute('data-v4-section-actions','true')}
function wireActions(state){if(document.documentElement.dataset.v4ActionsWired==='true')return;document.documentElement.dataset.v4ActionsWired='true';addSectionButtons();const buttons=[...document.querySelectorAll('button')];const exportButton=buttons.find(b=>/Exporter/i.test(b.textContent));if(exportButton)exportButton.addEventListener('click',()=>{const current=window.V4SourcingRuntime??state;const report={product:current.opportunity.product,score:current.opportunity.score,decision:current.opportunity.decision,reason:current.opportunity.decisionReason,evidenceLevel:current.opportunity.evidenceLevel,economics:current.economics,generatedAt:new Date().toISOString()};const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='v4-sourcing-intelligence-report.json';document.body.appendChild(a);a.click();a.remove();window.setTimeout(()=>URL.revokeObjectURL(url),250)});buttons.filter(b=>b.dataset.action==='new'||/Nouveau sourcing|Lancer une vérification/i.test(b.textContent)).forEach(b=>b.addEventListener('click',()=>{const product=window.prompt('Produit à analyser');if(product?.trim())startSourcing(product)}));const navTargets={'Dashboard':'.hero','Radar Sourcing':'.radar','Opportunités':'.table','Fournisseurs':'.table','Coût rendu':'.kpis .kpi:nth-child(2)','Échantillon & QC':'.section:last-of-type','Décisions':'.kpis .kpi:nth-child(5)','Rentabilité':'.signals','Veille & Alertes':'.diagnostic'};[...document.querySelectorAll('.nav a')].forEach(link=>link.addEventListener('click',event=>{event.preventDefault();document.querySelectorAll('.nav a').forEach(x=>x.classList.remove('on'));link.classList.add('on');const label=link.textContent.replace(/^[^\p{L}\p{N}€]+/u,'').trim();if(label==='Radar Sourcing'){const product=window.prompt('Produit à analyser');if(product?.trim())startSourcing(product)}else scrollToTarget(navTargets[label]||'.hero',label)}));document.querySelectorAll('[data-v4-section-action]').forEach(b=>b.addEventListener('click',()=>{const key=b.dataset.v4SectionAction;if(key==='radar'){const product=window.prompt('Produit à analyser');if(product?.trim())startSourcing(product)}else if(key==='opportunities')scrollToTarget('.table','Opportunités');else if(key==='diagnostic')scrollToTarget('.diagnostic','Diagnostic');else if(key==='qc')scrollToTarget('.section:last-of-type','Validation QC')}))}
export function initDashboardRuntime(opportunity=DEMO_OPPORTUNITY){try{const state=calculateDashboardState(opportunity);render(state);wireActions(state);document.documentElement.dataset.v4Runtime='ready';window.V4SourcingRuntime=Object.freeze(state);return state}catch(error){document.documentElement.dataset.v4Runtime='error';console.error('[V4 Sourcing] runtime initialization failed',error);sourcingStatus(opportunity?.product||'Produit inconnu','Erreur d’initialisation',true);return null}}
if(typeof document!=='undefined'){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>initDashboardRuntime(),{once:true});else initDashboardRuntime()}
